In [11]:
import numpy as np
import csv
import pandas as pd
import numpy as np
from random import randint, random

In [12]:
#Mix Server 1:
#-------------------------
x1=347       #private key(decyption key)
g=2         #generator(random)
#p=5766311893
p=4391
#p=656692050181897513638241554199181923922955921760928836766304161790553989228223793461834703506872747071705167995972707253940099469869516422893633357693
y1=pow(g,x1)%p

In [13]:
#Mix Server 2:
#-------------------------
x2=225        #private key(decyption key)
g=2         #generator(random)
#p=656692050181897513638241554199181923922955921760928836766304161790553989228223793461834703506872747071705167995972707253940099469869516422893633357693
y2=pow(g,x2)%p

In [14]:
print(y1, y2)

2261 2825


In [15]:
# Y* generation
y_star=(y1*y2)%p
y_star

2811

In [16]:
data=pd.read_csv("C:\\Users\\Jahid\\Desktop\\CSE 4000 Thesis\\Dataset\\data3.csv")
data

id  Size (Sq. feet)  Price (xK Tk)
0      0             1398           1573
1      1              589            538
2      2             1124           1158
3      3              836            962
4      4             1533           1444
..   ...              ...            ...
295  295             1091           1516
296  296              665            857
297  297             1238           1457
298  298              433            588
299  299             1178           1359

[300 rows x 3 columns]

In [17]:
x = data.iloc[:, 1:3].values
x

array([[1398, 1573],
       [ 589,  538],
       [1124, 1158],
       [ 836,  962],
       [1533, 1444],
       [1155, 1007],
       [ 725,  720],
       [1055, 1041],
       [ 722,  868],
       [ 989,  949],
       [1049, 1083],
       [1279, 1196],
       [1220, 1261],
       [1630, 1625],
       [1295, 1390],
       [ 833,  835],
       [1049,  918],
       [1336, 1430],
       [1202, 1092],
       [ 820,  849],
       [ 886,  997],
       [ 930,  910],
       [1373, 1177],
       [1073,  978],
       [1141, 1113],
       [1141, 1351],
       [1012, 1264],
       [ 710,  880],
       [ 932,  904],
       [1713, 1475],
       [ 196,  172],
       [1074, 1017],
       [ 988,  993],
       [1113, 1308],
       [1164, 1296],
       [ 751,  849],
       [ 910, 1050],
       [ 910, 1071],
       [ 659,  820],
       [ 767,  643],
       [1011, 1027],
       [1527, 1629],
       [1726, 1634],
       [ 728,  720],
       [ 809,  804],
       [ 923, 1135],
       [1319, 1176],
       [ 900,

In [18]:
def fisher_yates_shuffle(the_list):
    list_range = range(0, len(the_list))
    for i in list_range:
        j = randint(list_range[0], list_range[-1])
        the_list[i], the_list[j] = the_list[j], the_list[i]

In [27]:
import random
def shuffle_new(data):
    rand=[]
    for i in range(len(data)):
        rand.append(random.random())
    rand1=[]
    for i in range (len(data)):
        rand1.append(rand[i])
    rand.sort()
    
    index_rand=[]
    for i in range (len(data)):
        index_rand.append(rand1.index(rand[i]))
    area=[]
    price=[]
    for i in range (len(data)):
        area.append(data[i][0])
        price.append(data[i][1])
    for i in range (len(data)):
        data[i][0]=area[index_rand[i]]
        data[i][1]=price[index_rand[i]]
    return data

In [28]:
data_raw= np.zeros_like(x)
enc_c1= np.zeros_like(x)
enc_c2= np.zeros_like(x)

enc_c11= np.zeros_like(x)
enc_c22= np.zeros_like(x)

enc_c111= np.zeros_like(x)
enc_c222= np.zeros_like(x)
dec_data= np.zeros_like(x)

In [29]:
data_raw=x
data_raw

array([[1398, 1573],
       [ 589,  538],
       [1124, 1158],
       [ 836,  962],
       [1533, 1444],
       [1155, 1007],
       [ 725,  720],
       [1055, 1041],
       [ 722,  868],
       [ 989,  949],
       [1049, 1083],
       [1279, 1196],
       [1220, 1261],
       [1630, 1625],
       [1295, 1390],
       [ 833,  835],
       [1049,  918],
       [1336, 1430],
       [1202, 1092],
       [ 820,  849],
       [ 886,  997],
       [ 930,  910],
       [1373, 1177],
       [1073,  978],
       [1141, 1113],
       [1141, 1351],
       [1012, 1264],
       [ 710,  880],
       [ 932,  904],
       [1713, 1475],
       [ 196,  172],
       [1074, 1017],
       [ 988,  993],
       [1113, 1308],
       [1164, 1296],
       [ 751,  849],
       [ 910, 1050],
       [ 910, 1071],
       [ 659,  820],
       [ 767,  643],
       [1011, 1027],
       [1527, 1629],
       [1726, 1634],
       [ 728,  720],
       [ 809,  804],
       [ 923, 1135],
       [1319, 1176],
       [ 900,

In [30]:
#Encryption 1
for i in range(0,300):
    for j in range(0,2):
        #Encryption Data using Y* key
        data = data_raw[i][j]
        k=12    #random integer
        c1=pow(g,k)%p
        enc_c1[i][j]=c1
        c2=data*(pow(y_star,k)%p)
        enc_c2[i][j]=c2
        #print(c2)

In [31]:
enc_c2

array([[ 849984,  956384],
       [ 358112,  327104],
       [ 683392,  704064],
       [ 508288,  584896],
       [ 932064,  877952],
       [ 702240,  612256],
       [ 440800,  437760],
       [ 641440,  632928],
       [ 438976,  527744],
       [ 601312,  576992],
       [ 637792,  658464],
       [ 777632,  727168],
       [ 741760,  766688],
       [ 991040,  988000],
       [ 787360,  845120],
       [ 506464,  507680],
       [ 637792,  558144],
       [ 812288,  869440],
       [ 730816,  663936],
       [ 498560,  516192],
       [ 538688,  606176],
       [ 565440,  553280],
       [ 834784,  715616],
       [ 652384,  594624],
       [ 693728,  676704],
       [ 693728,  821408],
       [ 615296,  768512],
       [ 431680,  535040],
       [ 566656,  549632],
       [1041504,  896800],
       [ 119168,  104576],
       [ 652992,  618336],
       [ 600704,  603744],
       [ 676704,  795264],
       [ 707712,  787968],
       [ 456608,  516192],
       [ 553280,  638400],
 

In [32]:
#np.random.shuffle(enc_c2) 
#fisher_yates_shuffle(enc_c2)
shuffle_new(enc_c2)

array([[ 587328,  617728],
       [ 581856,  642656],
       [ 348384,  373920],
       [ 716224,  826272],
       [ 601312,  576992],
       [ 713184,  679744],
       [ 442016,  441408],
       [ 442624,  437760],
       [ 812288,  869440],
       [ 491872,  568480],
       [ 913824,  986784],
       [ 634752,  608608],
       [ 685216,  868832],
       [ 507072,  439584],
       [ 478496,  563008],
       [ 474240,  440192],
       [ 800128,  752096],
       [ 501600,  697984],
       [ 522272,  708928],
       [ 491872,  488832],
       [ 937536, 1054272],
       [ 668800,  766080],
       [ 713792,  685216],
       [1041504,  896800],
       [ 550240,  513152],
       [ 410400,  393376],
       [ 620768,  800128],
       [ 349600,  473632],
       [ 561184,  690080],
       [1034816, 1398400],
       [ 552064,  612256],
       [ 344736,  407360],
       [ 798304, 1037248],
       [ 637184,  648736],
       [ 538688,  606176],
       [ 421952,  435328],
       [ 456608,  516192],
 

In [33]:
#Encrytion phase 2
#coh1
for i in range(0,300):
    for j in range(0,2):
        enc_c11[i][j]=(enc_c1[i][j]*y1)
        #print("c11 = ",c11)
        temp2=pow(y_star,x1)%p
        enc_c22[i][j]=(enc_c2[i][j]*temp2)
        #print("encryption2: ",c22)

In [34]:
enc_c22

array([[116290944, 122310144],
       [115207488, 127245888],
       [ 68980032,  74036160],
       [141812352, 163601856],
       [119059776, 114244416],
       [141210432, 134589312],
       [ 87519168,  87398784],
       [ 87639552,  86676480],
       [160833024, 172149120],
       [ 97390656, 112559040],
       [180937152, 195383232],
       [125680896, 120504384],
       [135672768, 172028736],
       [100400256,  87037632],
       [ 94742208, 111475584],
       [ 93899520,  87158016],
       [158425344, 148915008],
       [ 99316800, 138200832],
       [103409856, 140367744],
       [ 97390656,  96788736],
       [185632128, 208745856],
       [132422400, 151683840],
       [141330816, 135672768],
       [206217792, 177566400],
       [108947520, 101604096],
       [ 81259200,  77888448],
       [122912064, 158425344],
       [ 69220800,  93779136],
       [111114432, 136635840],
       [204893568, 276883200],
       [109308672, 121226688],
       [ 68257728,  80657280],
       [

In [36]:
#fisher_yates_shuffle(enc_c22)
#np.random.shuffle(enc_c22) 
shuffle_new(enc_c22)
enc_c22

array([[132422400, 161194176],
       [ 60673536,  58627008],
       [161314560, 189002880],
       [ 85472640, 105937920],
       [ 52126272,  70785792],
       [130496256, 141691968],
       [132422400, 151683840],
       [127005120, 159147648],
       [196225920, 195624000],
       [112318272, 110030976],
       [152285760, 179372160],
       [140126976, 156017664],
       [204893568, 276883200],
       [158064192, 205375104],
       [110030976,  96547968],
       [132061248, 149035392],
       [122912064, 143256960],
       [ 65850048,  68618880],
       [140247360, 146025792],
       [ 62479296,  58145472],
       [ 86796864,  84509568],
       [183826368, 196105536],
       [152406144, 147951936],
       [ 89565696, 125560512],
       [ 78008832,  89445312],
       [100641024, 115809408],
       [143377344, 179372160],
       [127245888, 162277632],
       [148192704, 149757696],
       [ 97631424, 125801280],
       [139043520, 121226688],
       [ 53209728,  54172800],
       [

In [37]:
#Encrytion phase 3
#coh3
for i in range(0,300):
    for j in range(0,2):
        enc_c111[i][j]=(enc_c11[i][j]*y2)
        #print("c11 = ",c11)
        temp2=pow(y_star,x2)
        x=int(enc_c22[i][j]/(pow(y_star,x1)%p))
        enc_c222[i][j]=x*(((pow(y_star,x1)%p)*temp2)%p)
        

In [38]:
enc_c222

array([[1016576000, 1237450240],
       [ 465776640,  450065920],
       [1238374400, 1450931200],
       [ 656153600,  813260800],
       [ 400161280,  543406080],
       [1001789440, 1087736320],
       [1016576000, 1164441600],
       [ 974988800, 1221739520],
       [1506380800, 1501760000],
       [ 862241280,  844682240],
       [1169062400, 1376998400],
       [1075722240, 1197711360],
       [1572920320, 2125568000],
       [1213422080, 1576616960],
       [ 844682240,  741176320],
       [1013803520, 1144110080],
       [ 943567360, 1099750400],
       [ 505515520,  526771200],
       [1076646400, 1121006080],
       [ 479639040,  446369280],
       [ 666319360,  648760320],
       [1411192320, 1505456640],
       [1169986560, 1135792640],
       [ 687575040,  963898880],
       [ 598855680,  686650880],
       [ 772597760,  889041920],
       [1100674560, 1376998400],
       [ 976837120, 1245767680],
       [1137640960, 1149655040],
       [ 749493760,  965747200],
       [10

In [39]:
#fisher_yates_shuffle(enc_c222)
#np.random.shuffle(enc_c222)
shuffle_new(enc_c222)
enc_c222

array([[ 720844800,  669091840],
       [1213422080, 1576616960],
       [ 495349760,  504591360],
       [ 465776640,  450065920],
       [ 696816640,  667243520],
       [1054466560, 1248540160],
       [ 896435200,  914918400],
       [ 633973760,  803095040],
       [1173683200, 1269795840],
       [1024893440, 1355742720],
       [ 707906560,  858544640],
       [ 861317120,  835440640],
       [ 408478720,  415872000],
       [1038755840, 1070177280],
       [ 964823040,  925084160],
       [ 958353920,  995320320],
       [ 582220800,  646912000],
       [1140413440, 1196787200],
       [1040604160, 1280885760],
       [ 644139520,  650608640],
       [ 976837120, 1245767680],
       [1064632320, 1011955200],
       [1174607360, 1513774080],
       [1213422080, 1518394880],
       [1380695040, 1575692800],
       [ 813260800,  820654080],
       [ 975912960, 1208801280],
       [ 811412480,  999016960],
       [1034135040, 1407495680],
       [ 841909760, 1047997440],
       [11

In [40]:
#Decyption phase
temp5=k*(x1+x2)
temp6=(x1+x2)*(x1+x2)
temp7=(pow(g,temp5)%p)*(pow(g,temp6)%p)
print(temp7)
dec_data=enc_c222/temp7
dec_data = np.asarray(dec_data, dtype = 'int')

924160


In [41]:
dec_data

array([[ 780,  724],
       [1313, 1706],
       [ 536,  546],
       [ 504,  487],
       [ 754,  722],
       [1141, 1351],
       [ 970,  990],
       [ 686,  869],
       [1270, 1374],
       [1109, 1467],
       [ 766,  929],
       [ 932,  904],
       [ 442,  450],
       [1124, 1158],
       [1044, 1001],
       [1037, 1077],
       [ 630,  700],
       [1234, 1295],
       [1126, 1386],
       [ 697,  704],
       [1057, 1348],
       [1152, 1095],
       [1271, 1638],
       [1313, 1643],
       [1494, 1705],
       [ 880,  888],
       [1056, 1308],
       [ 878, 1081],
       [1119, 1523],
       [ 911, 1134],
       [1231, 1244],
       [ 396,  514],
       [ 907,  974],
       [1215, 1380],
       [1173, 1118],
       [1044, 1168],
       [1113, 1308],
       [ 573,  615],
       [ 988,  993],
       [ 665,  857],
       [ 665,  797],
       [ 906,  972],
       [1055, 1041],
       [ 859, 1166],
       [ 744,  732],
       [ 783,  751],
       [1337, 1832],
       [1175,

In [44]:
area=dec_data[:,0]
area

array([ 780, 1313,  536,  504,  754, 1141,  970,  686, 1270, 1109,  766,
        932,  442, 1124, 1044, 1037,  630, 1234, 1126,  697, 1057, 1152,
       1271, 1313, 1494,  880, 1056,  878, 1119,  911, 1231,  396,  907,
       1215, 1173, 1044, 1113,  573,  988,  665,  665,  906, 1055,  859,
        744,  783, 1337, 1175,  961, 1196, 1118, 1073,  589,  811, 1069,
        646,  961, 1174,  433,  728, 1028, 1495, 1217, 1178,  908,  675,
       1046,  957, 1409, 1264, 1451, 1861, 1074,  900,  685, 1039, 1355,
       1126, 1191, 1021, 1265,  939,  744, 1008,  567,  572, 1517, 1323,
        579, 1071, 1048, 1100, 1266,  487,  947,  710,  575,  436, 1316,
        744,  809, 1074,  980,  802,  717, 1021, 1285, 1073, 1000, 1051,
       1527, 1150, 1503,  704,  905,  722, 1049, 1398, 1102,  749, 1283,
       1256,  519, 1251,  744, 1702, 1122,  855,  972,  667,  930,  923,
       1062,  996, 1152,  803, 1094, 1423,  416,  868,  820,  870, 1128,
        638, 1726, 1630, 1011, 1402,  910,  845,  8

In [45]:
price=dec_data[:,1]
price

array([ 724, 1706,  546,  487,  722, 1351,  990,  869, 1374, 1467,  929,
        904,  450, 1158, 1001, 1077,  700, 1295, 1386,  704, 1348, 1095,
       1638, 1643, 1705,  888, 1308, 1081, 1523, 1134, 1244,  514,  974,
       1380, 1118, 1168, 1308,  615,  993,  857,  797,  972, 1041, 1166,
        732,  751, 1832, 1609, 1282, 1439, 1165,  978,  538, 1045, 1357,
        775, 1271, 1127,  588,  720,  964, 2034, 1169, 1359, 1007,  647,
       1361, 1057, 1710, 1496, 1989, 2237, 1178,  798,  751, 1183, 1190,
       1193, 1490, 1316, 1316, 1145,  877, 1067,  670,  513, 1413, 1375,
        632, 1202, 1067, 1260, 1229,  534, 1036,  880,  779,  518, 1237,
       1043,  769, 1017, 1184,  819,  862, 1190, 1242, 1154, 1288, 1143,
       1629, 1498, 1623,  809,  844,  868,  918, 1573, 1369,  837, 1555,
       1388,  483, 1308,  763, 2300, 1554, 1174, 1308,  630,  910, 1135,
       1376, 1186, 1282,  875, 1217, 1678,  351,  867,  849, 1049, 1282,
        629, 1634, 1625, 1027, 1753, 1071, 1045,  8

# Apply block nested loop

In [46]:
#area=[209,262,264,279,244,234,207,245,139,295,183,129,209,200,200]
#price=[735,912,1003,1065,1282,1247,1032,1235,441,964,680,439,700,439,439]
skyline_area=[]
skyline_price=[]
skyline_area.append(area[0])
skyline_price.append(price[0])
#print(skyline)

def is_dominated(area1,price1):
	c = 0
	for (i,j) in zip(skyline_area,skyline_price):

		if(i >= area1 and j <= price1):
			c = c + 1
	return c

def is_dominate(area1,price1):
	c = 0
	for (i,j) in zip(skyline_area,skyline_price):
		#print(area1,price1)
		if(i <= area1 and j <= price1):
			#skyline_area.remove(i)
			#skyline_price.remove(j)   
			#i=i-1
			#j=j-1
			c = c + 1
	return c

for (i,j) in zip(area,price):
	x=is_dominated(i,j)
	#print("x=",x)
	if(x==0):
		skyline_area.append(i)
		skyline_price.append(j)
		y = is_dominate(i,j)
		#print("y=",y)
		if(y>0):
			k=0
			while k < (len(skyline_area)-1):
				if(skyline_area[k]<=i and skyline_price[k]>=j):
					skyline_area.pop(k)
					skyline_price.pop(k)
					k=k   
				else:
					k+=1
					
				#print(skyline_area)
				#print(skyline_price)

print(skyline_area)
print(skyline_price)

[442, 1073, 589, 1217, 1861, 900, 572, 1517, 1049, 519, 416, 1726, 914, 1058, 1319, 1060, 1475, 746, 196, 767, 247, 834, 1533, 1126, 1003, 1713, 1373, 1155, 603, 1493, 1202, 582, 1900, 1775]
[450, 978, 538, 1169, 2237, 798, 513, 1413, 918, 483, 351, 1634, 802, 931, 1176, 971, 1336, 629, 172, 643, 229, 723, 1444, 980, 859, 1475, 1177, 1007, 546, 1349, 1092, 519, 2491, 1962]


In [47]:
len(skyline_area)

34

# Apply bitmap algo

In [48]:
#area=[209,262,264,279,244,234,207,245,139,295,183,129,209,200,200]
#price=[735,912,1003,1065,1282,1247,1032,1235,441,964,680,439,700,439,439]



area1=area
price1=price
area = list((area))
area.sort(reverse=True)
price = list((price))
price.sort()
area2=[]
price2=[]

for i in range (len(area1)):
	area2.append(area.index(area1[i])+1)

for i in range (len(price1)):
	price2.append(price.index(price1[i])+1)

for i in range (len(area1)):
	if(area2[i]==area2[i-1] and price2[i]==price2[i-1]):
		area2[i]=area2[i]+1
		price2[i]=price2[i]+1


area3=[]
price3=[]
x=len(area)+1
str1=""
for i in range (len(area2)):
	x1=x-(area2[i]+1)+1
	for j in range (x1):
		str1+="1"
	for k in range ((x-x1)-1):
		str1+="0"
	area3.append(str1)
	str1=""

str2=""
for i in range (len(price2)):
	x2=x-(price2[i]+1)+1
	for j in range (x2):
		str2+="1"
	for k in range ((x-x2)-1):
		str2+="0"
	price3.append(str2)
	str2=""	
#for i in range (len(area3)):
	#print(area3[i],price3[i])
	#i+=1


def f1(xx,yy):
	str3=""
	str4=""
	str7=""
	for i in range (len(area3)):
		str5=area3[i]
		x5=x-xx
		x5=x5-1
		str3+=str5[x5]
	for i in range (len(price3)):
		str6=price3[i]
		x6=x-yy
		x6=x6-1
		str4+=str6[x6]
	for i in range (len(str3)):
		if(str3[i]=='1' and str4[i]=='1'):
			str7+='1'
		else:
			str7+='0'

	c=0
	for i in range (len(str7)):
		if(str7[i]=='1'):
			c+=1
	return c

skyline_area=[]
skyline_price=[]

for i in range (len(area2)):
	ans= f1(area2[i],price2[i])
	if(ans==1):
		skyline_area.append(area1[i])
		skyline_price.append(price1[i])


print(skyline_area)
print(skyline_price)

[442, 1073, 589, 1217, 1861, 900, 572, 1517, 1049, 519, 416, 1726, 914, 1058, 1319, 1060, 1475, 746, 196, 767, 247, 834, 1533, 1126, 1003, 1713, 1373, 1155, 603, 1493, 1202, 582, 1900, 1775]
[450, 978, 538, 1169, 2237, 798, 513, 1413, 918, 483, 351, 1634, 802, 931, 1176, 971, 1336, 629, 172, 643, 229, 723, 1444, 980, 859, 1475, 1177, 1007, 546, 1349, 1092, 519, 2491, 1962]


In [49]:
len(skyline_area)

34

# Apply nearest neighbour

In [51]:
#area=[209,262,264,279,244,234,207,245,139,295,183,129,209,200,200]
#price=[735,912,1003,1065,1282,1247,1032,1235,441,964,680,439,700,439,439]

area=dec_data[:,0]
area
price=dec_data[:,1]
price

area3=area
price3=price

area1=area
price1=price
area = list(set(area))
area.sort(reverse=True)
price = list(set(price))
price.sort()
area2=[]
price2=[]
for i in range (len(area1)):
	area2.append(area.index(area1[i])+1)

for i in range (len(price1)):
	price2.append(price.index(price1[i])+1)

mx=max(area2)
nn = []
for i in range (len(area2)):
	nn.append((area2[i]+price2[i],i))

skyline_area=[]
skyline_price=[]

nn.sort()

i=0
while len(nn)!=0:
	skyline_area.append(area2[nn[i][1]])
	skyline_price.append(price2[nn[i][1]])
	
	#xmn=int(area2[nn[0][1]]),ymin=int(price2[nn[0][1]])
	k=i
	
	while k < (len(nn)):
		l=len(skyline_area)
		if(area2[nn[k][1]]>=skyline_area[l-1] and price2[nn[k][1]]>=skyline_price[l-1]):
			nn.pop(k)
			#print(nn)
			k=k
		else:
			k=k+1
		#print(nn)

skyline_area1=[]
skyline_price1=[]
for i in range (len(skyline_area)):
	skyline_area1.append(area[skyline_area[i]-1])

for i in range (len(skyline_price)):
	skyline_price1.append(price[skyline_price[i]-1])
	
print(skyline_area1)
print(skyline_price1)

[1373, 1126, 1155, 1319, 1202, 1058, 1049, 1003, 1073, 1060, 1475, 1217, 914, 1493, 900, 834, 767, 746, 1517, 1713, 1533, 582, 589, 603, 572, 1726, 519, 442, 416, 196, 247, 1775, 1861, 1900]
[1177, 980, 1007, 1176, 1092, 931, 918, 859, 978, 971, 1336, 1169, 802, 1349, 798, 723, 643, 629, 1413, 1475, 1444, 519, 538, 546, 513, 1634, 483, 450, 351, 172, 229, 1962, 2237, 2491]


In [52]:
len(skyline_area1)

34